package model.am;

import java.sql.CallableStatement;

import java.sql.SQLException;

import model.am.common.Naresco_AM;

import model.vo.PAYROLL_LINES_VOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 12 21:09:47 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Naresco_AMImpl extends ApplicationModuleImpl implements Naresco_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Naresco_AMImpl() {
    }

    /**
     * Container's getter for PAYROLL_HDR_VO.
     * @return PAYROLL_HDR_VO
     */
    public ViewObjectImpl getPAYROLL_HDR_VO() {
        return (ViewObjectImpl) findViewObject("PAYROLL_HDR_VO");
    }

    /**
     * Container's getter for PAYROLL_LINES_VO.
     * @return PAYROLL_LINES_VO
     */
    public PAYROLL_LINES_VOImpl getPAYROLL_LINES_VO() {
        return (PAYROLL_LINES_VOImpl) findViewObject("PAYROLL_LINES_VO");
    }

    /**
     * Container's getter for Payroll_Hdr_Line_VL.
     * @return Payroll_Hdr_Line_VL
     */
    public ViewLinkImpl getPayroll_Hdr_Line_VL() {
        return (ViewLinkImpl) findViewLink("Payroll_Hdr_Line_VL");
    }
    public String callingReportPkg(String buid,String date)
    {
            try {
                        String stmt1 = "begin XXSC_OTL_REPORT_PKG.INSERT_PAYROLL_LINE_PR(:p_bu_id,:p_date); end;";
                        CallableStatement cst = null;
                        cst = this.getDBTransaction().createCallableStatement(stmt1,0);
                        cst.setObject("p_bu_id", buid);
                        cst.setObject("p_date", date);
                        
                        cst.executeUpdate();
return "success";
                    } catch (SQLException e) {
                        e.printStackTrace();
                        
                    }
            
        
        
        return  "error";
        }
        
}

